# Generated by Django 4.2.1 on 2023-05-15 18:41

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('chats', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chat',
            name='members',
            field=models.ManyToManyField(null=True, related_name='chat_members', to=settings.AUTH_USER_MODEL),
        ),
    ]
