# Generated by Django 4.2.1 on 2023-05-15 21:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chats', '0003_alter_chat_members'),
    ]

    operations = [
        migrations.AddField(
            model_name='chat',
            name='isForked',
            field=models.BooleanField(default=False, null=True),
        ),
    ]
