# Generated by Django 4.2.1 on 2023-05-15 21:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chats', '0004_chat_isforked'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='chat',
            options={'ordering': ['-created_at']},
        ),
        migrations.RenameField(
            model_name='chat',
            old_name='isForked',
            new_name='is_forked',
        ),
        migrations.RenameField(
            model_name='chat',
            old_name='isPrivate',
            new_name='is_private',
        ),
        migrations.RenameField(
            model_name='chat',
            old_name='isPublic',
            new_name='is_public',
        ),
    ]
