# Generated by Django 4.2.1 on 2023-05-17 09:13

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('chats', '0005_alter_chat_options_rename_isforked_chat_is_forked_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chat',
            name='members',
            field=models.ManyToManyField(default=models.ForeignKey(default='deleted user', on_delete=django.db.models.deletion.SET_DEFAULT, related_name='chats', to=settings.AUTH_USER_MODEL), related_name='chat_members', to=settings.AUTH_USER_MODEL),
        ),
    ]
