# Generated by Django 4.2.1 on 2023-05-19 18:16

import chats.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chats', '0008_remove_chat_is_private_remove_chat_members'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chat',
            name='chats',
            field=models.JSONField(blank=True, default=chats.models.get_default_chat, null=True),
        ),
    ]
